import numpy as np
import pandas as pd
from scipy.special import softmax
from scipy.special import logsumexp
from openfhe import *
import openfhe_numpy as onp
from openfhe_numpy.tensor.ctarray import CTArray
from openfhe_numpy import ArrayEncodingType


def select_columns(matrix, start, end):
    n_cols = matrix.shape[-1]
    n_selected = end - start
    
    # Create selection matrix: (n_cols, n_selected)
    # Each column j has a 1 at position (start + j)

    # Mayank: Create the selection matrix and encrypt it
    selection_matrix = np.zeros((n_cols, n_selected))
    for i in range(n_selected):
        selection_matrix[start + i, i] = 1.0
    
    # Matrix multiplication: (rows, n_cols) @ (n_cols, n_selected) = (rows, n_selected)
    return matrix @ selection_matrix

def slice_vector(vector, start, end):
    length = vector.shape[0]
    slice_length = end - start
    
    # Create selection matrix: (slice_length, length)
    # Each row i has a 1 at position (start + i)
    selection_matrix = np.zeros((slice_length, length))
    for i in range(slice_length):
        selection_matrix[i, start + i] = 1.0
    
    # Matrix-vector multiplication: (slice_length, length) @ (length,) = (slice_length,)
    return selection_matrix @ vector

def transform_marginal(marginal_enc):
    size = len(marginal_enc)
    sz = 1
    while sz < size:
        sz *= 2
    new_marginal = []
    for i in range(len(marginal_enc)):
        new_marginal.append(CTArray(
            marginal_enc[i].data, marginal_enc[0].shape, marginal_enc[0].batch_size, (sz, 1), ArrayEncodingType.ROW_MAJOR
        ))

    return new_marginal

def dot_product(vec1, vec2, keys):
    dot_product_enc = (vec1 @ vec2)
    dot_product_enc *= (1 / (vec1.batch_size // 8))
    # print(f"Multiplying {vec1.decrypt(keys.secretKey, unpack_type="original")} and {vec2.decrypt(keys.secretKey, unpack_type="original")}")
    vec1_dec = vec1.decrypt(keys.secretKey, unpack_type="original")
    vec2_dec = vec2.decrypt(keys.secretKey, unpack_type="original")

    expected = np.dot(vec1_dec, vec2_dec)
    computed = dot_product_enc.decrypt(keys.secretKey, unpack_type="original")

    # print(expected, computed)
    # breakpoint()

    return dot_product_enc

def slice_vector_he(enc_vec, start, end, keys, debug=False):
    """
    Slice an encrypted vector while keeping it encrypted using matrix multiplication.
    
    Treat the vector of length n as a matrix of shape (1, n).
    Create a selection mask in numpy which is 0 everywhere except for the range [start, end)
    Matrix multiply the selection matrix with the original vector to get the sliced result. 
    
    Parameters
    ----------
    enc_vec :  CTArray
        The encrypted vector to slice (in ROW_MAJOR format)
    start : int
        Start index (inclusive)
    end : int
        End index (exclusive)
    keys:
        The keys generated by the cryptocontext (cc.KeyGen())
    
    Returns
    -------
    CTArray
        The sliced encrypted vector containing elements from index start to end-1
    """
    slice_length = end - start
    length = enc_vec.original_shape[0]

    selection_matrix = np.zeros((slice_length, length))
    for i in range(slice_length):
        selection_matrix[i, start + i] = 1.0
    
    if debug:
        breakpoint()

    enc_selection = onp.array(
        cc=enc_vec.data.GetCryptoContext(),
        data=selection_matrix,
        batch_size=enc_vec.batch_size,
        order=onp.ROW_MAJOR,
        mode="tile",
        fhe_type="C",
        public_key=keys.publicKey,
    )
    enc_selection.extra["colkey"] = onp.sum_col_keys(keys.secretKey) # maybe this can be moved outside so only public key would be needed in this function
    # enc_selection.extra["rowkey"] = onp.sum_row_keys(keys.secretKey, enc_selection.ncols, enc_selection.batch_size) # needed for row sum

    slice_result = enc_selection @ enc_vec
    return slice_result

def select_column_he(mat_enc, column, crypto_context, keys):
    """
    Method to select column from encrypted matrix.
    Equivalent to mat_enc[:, column] in numpy
    """
    selection_vector = np.zeros(mat_enc.original_shape[1])
    selection_vector[column] = 1.0
    
    # encrypt selection_vector
    selection_vector_enc = onp.array(
            cc=crypto_context,
            data=selection_vector,
            batch_size=mat_enc.batch_size,
            order=onp.COL_MAJOR,
            mode="tile",
            fhe_type="C",
            public_key=keys.publicKey,
        )
    selected_column_enc =  mat_enc @ selection_vector_enc

    return selected_column_enc


def decrypt_and_print(entity, keys):
    decrypted = entity.decrypt(keys.secretKey, unpack_type="original")
    print(decrypted)

def encrypt(data, crypto_context, keys, order="ROW_MAJOR"):
    """
    Here data is encrypted using the crypto_context and the keys.
    We are using 'tile' packing here
    """

    if order == "ROW_MAJOR":
        order = onp.ROW_MAJOR
    else:
        order = onp.COL_MAJOR

    batch_size = crypto_context.GetRingDimension() // 2

    enc_data = onp.array(
        cc=crypto_context,
        data=data,
        batch_size=batch_size,
        order=order,
        mode="tile",
        fhe_type="C",
        public_key=keys.publicKey
    )

    return enc_data

def check(encrypted, clear, keys):
    print("Checking now....")
    for e, c in zip(encrypted, clear):
        dec = e.decrypt(keys.secretKey, unpack_type="original")
        print(np.abs(dec-c).sum())


class HE_Computations:
    def __init__(self, domain, workload_domain_size, candidates, enc_noise_measure, enc_noise_select):
        self.domain = domain
        self.workload_domain_size = workload_domain_size
        self.candidates = candidates

        self.setup_crypto_context()

        # self.crypto_context and self.keys are available after this

        self.answers_encrypted = None
        self.used_up_guassian_samples = 0
        self.used_up_gumble_samples = 0
        self.enc_noise_measure = encrypt(enc_noise_measure, self.crypto_context, self.keys, order="COL_MAJOR") # encrypt measure noise here
        self.enc_noise_select = encrypt(enc_noise_select, self.crypto_context, self.keys, order="COL_MAJOR") # encrypt select noise here

        # Pre-compute column indices for each attribute in OHE matrix
        self.attr_column_ranges = {}
        col_offset = 0
        for attr in domain.attrs:
            n_bins = domain[attr]
            self.attr_column_ranges[attr] = (col_offset, col_offset + n_bins)
            col_offset += n_bins
    
    def setup_crypto_context(self):
        """
        Here we define the CKKS FHE parameters and define the crypto context for encoding, encryption, decryption and decoding
        We set the crypto_context and keys here
        """
        mult_depth = 10

        params = CCParamsCKKSRNS()
        params.SetMultiplicativeDepth(mult_depth)
        params.SetScalingModSize(59)
        params.SetFirstModSize(60)
        params.SetScalingTechnique(FIXEDAUTO)
        params.SetKeySwitchTechnique(HYBRID)
        params.SetSecretKeyDist(UNIFORM_TERNARY)

        cc = GenCryptoContext(params)
        cc.Enable(PKESchemeFeature.PKE)
        cc.Enable(PKESchemeFeature.LEVELEDSHE)
        cc.Enable(PKESchemeFeature.ADVANCEDSHE)

        keys = cc.KeyGen()

        cc.EvalMultKeyGen(keys.secretKey)
        cc.EvalSumKeyGen(keys.secretKey)

        self.crypto_context = cc
        self.keys = keys


    # add chunking method for noise        

    def compute(self, enc_data):
        """
        Compute marginals for all candidates using OHE data.

        Args:
            enc_data: One-hot encoded data matrix (n_records, total_bins)

        Returns:
            list: List of marginals where index corresponds to candidates list
        """
        answers_enc = []
        answers = []

        # Mayank: preprocess the oneway marginals with row-sums

        # @FHE: Encrypt enc_data here
        self.enc_data = encrypt(enc_data, self.crypto_context, self.keys)
        self.enc_data.extra["colkey"] = onp.sum_col_keys(self.keys.secretKey)
        self.enc_data.extra["rowkey"] = onp.sum_row_keys(self.keys.secretKey, self.enc_data.ncols, self.enc_data.batch_size) # needed for row sum
        self.oneway = onp.sum(self.enc_data, axis=0) * (1/256) # need to figure out this correction factor
        # self.oneway = encrypt(enc_data.sum(axis=0), self.crypto_context, self.keys, order="ROW_MAJOR")
        breakpoint()

        for cl in self.candidates:
            print(f"Computing marginal for {cl}")
            marginal = None
            if len(cl) == 1:
                # One-way marginal: sum across columns
                marginal = self._compute_oneway_he(enc_data, cl[0])

                marginal_clear = self._compute_oneway(enc_data, cl[0])

            elif len(cl) == 2:
                continue # remove after debugging
                # Two-way marginal: element-wise multiply and sum
                marginal = self._compute_twoway_he(self.enc_data, cl[0], cl[1])

                marginal_clear = self._compute_twoway(enc_data, cl[0], cl[1])
            else:
                # K-way marginal
                continue
                # marginal = self._compute_kway(enc_data, cl)
            if marginal is not None:
                answers_enc.append(marginal)
                answers.append(marginal_clear)
        self.answers_encrypted = answers_enc

        check(answers_enc, answers, self.keys)
        breakpoint()
        #return answers_enc

    def compute_he(self, enc_data):
        """
        Docstring for compute_he
        
        :param enc_data: encrypted one hot encoded data

        sets/returns:
            answers_enc: list of row sums of 1-way and 2-way marginals
        """
        pass

    def _compute_oneway(self, enc_data, attr):
        """
        Compute one-way marginal for a single attribute.
        Sum across columns corresponding to that attribute.
        """
        start_col, end_col = self.attr_column_ranges[attr]
        # Sum across columns: ω(N-1) additions
        marginal = np.sum(enc_data[:, start_col:end_col], axis=0)
        return marginal
    
    def _compute_oneway_he(self, enc_data, attr):
        """
        HE-emulation of one-way marginal.

        Model:
        - Each row of enc_data is conceptually an encrypted ciphertext
            with d packed slots.
        - We accumulate rows using a loop (ciphertext additions).
        - We rotate once to bring the attribute block to the front.

        Contract:
        - Let width = end_col - start_col.
        - The first `width` slots of the returned vector contain:
                np.sum(enc_data[:, start_col:end_col], axis=0)
        - All remaining slots are undefined and must be ignored.

        No masking is performed.
        """
        start_col, end_col = self.attr_column_ranges[attr]
        length = end_col - start_col

        # select start_col to end_col from self.oneway vector
        marginal = slice_vector_he(self.oneway, start_col, end_col, self.keys)

        return marginal
    
    def _compute_twoway(self, enc_data, attr1, attr2):
        """
        Compute two-way marginal for two attributes.
        Element-wise multiply columns and sum.
        """
        start1, end1 = self.attr_column_ranges[attr1]
        start2, end2 = self.attr_column_ranges[attr2]
        # Get columns for each attribute
        cols1 = select_columns(enc_data, start1, end1)  # shape: (N, ω1)
        cols2 = select_columns(enc_data, start2, end2)  # shape: (N, ω2)

        marginal = cols1.T @ cols2

        return marginal.flatten()
    
    def _compute_twoway_he(self, enc_mat, attr1, attr2):
        """
        Need select_column
        """
        start1, end1 = self.attr_column_ranges[attr1]
        start2, end2 = self.attr_column_ranges[attr2]

        dot_prod = []
        print("Gathering the dot products...")
        for i in range(start1, end1):
            col1 = select_column_he(enc_mat, i, self.crypto_context, self.keys)
            for j in range(start2, end2):
                col2 = select_column_he(enc_mat, j, self.crypto_context, self.keys)
                dot_prod.append(dot_product(col1, col2, self.keys))

        marginal = np.zeros(len(dot_prod))
        marginal_enc_cum = onp.array(
                cc=self.crypto_context,
                data=marginal,
                batch_size=self.enc_data.batch_size,
                order=onp.ROW_MAJOR,
                mode="tile",
                fhe_type="C",
                public_key=self.keys.publicKey,
            )

        marginal_transformed_enc = transform_marginal(dot_prod)
        print("Arranging the dot_products...")
        for i in range(len(marginal_transformed_enc)):
            selection_vector = np.zeros(len(marginal_transformed_enc))
            selection_vector[i] = 1.0
            # encrypt it
            selection_vector_enc = onp.array(
                cc=self.crypto_context,
                data=selection_vector,
                batch_size=self.enc_data.batch_size,
                order=onp.ROW_MAJOR,
                mode="tile",
                fhe_type="C",
                public_key=self.keys.publicKey,
            )
            
            marginal_enc_cum += selection_vector_enc * marginal_transformed_enc[i]
        print("Done with the dot products!!")
        return marginal_enc_cum


    def _compute_kway(self, enc_data, clique):
        """
        Compute k-way marginal for k attributes.
        """
        # Get columns for each attribute in the clique
        columns = []
        shapes = []
        for attr in clique:
            start, end = self.attr_column_ranges[attr]
            columns.append(enc_data[:, start:end])
            shapes.append(end - start)

        # Create k-dimensional marginal
        marginal = np.zeros(shapes)

        # Generate all combinations of bin indices
        from itertools import product
        for indices in product(*[range(s) for s in shapes]):
            # Element-wise multiply across all attributes
            result = np.ones(enc_data.shape[0])
            for col_idx, bin_idx in enumerate(indices):
                result *= columns[col_idx][:, bin_idx]
            marginal[indices] = np.sum(result)

        return marginal.flatten()


    def measure(self, marginal_index, sigma):
        # we can add checks here on whether enough samples are available, if not waht to do, some logs and debug
        marginal = self.answers_encrypted[marginal_index]
        # n_samples = len(marginal) # Mayank: this can also be computed using the start and end indices
        n_samples = marginal.original_shape[0]
        noise = slice_vector_he(self.enc_noise_measure, self.used_up_guassian_samples, self.used_up_guassian_samples + n_samples, self.keys)
        self.used_up_guassian_samples += n_samples
        breakpoint()
        y_enc = marginal + noise * sigma
        # y_enc = marginal + noise * float(sigma) # @FHE there is some shape error here, shape of marginal != shape of noise

        # @FHE: before returning, y_enc needs to be decrypted
        y_dec = marginal.decrypt(self.keys.secretKey, unpack_type="original") + sigma * noise.decrypt(self.keys.secretKey, unpack_type="original")

        return y_dec

    def select_measure_worst(self,candidates_indices, est_ans, epsilon, sigma, max_sensitivity,bias,wgt):
        errors = np.array([])
        # Select
        for marginal_index in candidates_indices.values():
            #reduce number of additions by taking only domain size
            bias_ = bias[marginal_index]
            wgt_ = wgt[marginal_index]
            x = self.answers_encrypted[marginal_index]
            breakpoint()
            xest = est_ans[marginal_index] # Mayank: this will need to be encoded into a plain text
            
            # encode xest to plaintext

            err = wgt_ * (np.linalg.norm(x - xest, 1) - bias_) 
            # Mayank: in real HE implementation, the irrelevant slots in the ciphertext
            # should not contribute to the error
            # noise = self.enc_noise_select[self.used_up_gumble_samples] # @FHE: uncomment after figuring this out
            self.used_up_gumble_samples += 1
            # err = err + (2 * max_sensitivity / epsilon) * noise @FHE: uncomment after figuring this out
            errors = np.append(errors, err)

        cl_dec = np.argmax(errors) # this is the index of the query in encrypted form

        # Measure
        marginal = self.answers_encrypted[cl_dec]
        n_samples = len(marginal)
        noise = slice_vector(self.enc_noise_measure, self.used_up_guassian_samples, self.used_up_guassian_samples + n_samples)
        self.used_up_guassian_samples += n_samples
        y_enc = marginal + sigma * noise
        cl = next((key for key, value in candidates_indices.items() if value == cl_dec), None)

        return cl, y_enc
